/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCampaignsJoinRouteImport } from './routes/_authenticated/campaigns.join'
import { Route as AuthenticatedCampaignsCreateRouteImport } from './routes/_authenticated/campaigns.create'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as ApiPublicSpotifyCallbackRouteImport } from './routes/api/public/spotify/callback'
import { Route as AuthenticatedCampaignsIdPlayRouteImport } from './routes/_authenticated/campaigns.$id_.play'
import { Route as AuthenticatedCampaignsIdCharacterRouteImport } from './routes/_authenticated/campaigns.$id_.character'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsJoinRoute =
  AuthenticatedCampaignsJoinRouteImport.update({
    id: '/campaigns/join',
    path: '/campaigns/join',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsCreateRoute =
  AuthenticatedCampaignsCreateRouteImport.update({
    id: '/campaigns/create',
    path: '/campaigns/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSpotifyCallbackRoute =
  ApiPublicSpotifyCallbackRouteImport.update({
    id: '/api/public/spotify/callback',
    path: '/api/public/spotify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCampaignsIdPlayRoute =
  AuthenticatedCampaignsIdPlayRouteImport.update({
    id: '/campaigns/$id_/play',
    path: '/campaigns/$id/play',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdCharacterRoute =
  AuthenticatedCampaignsIdCharacterRouteImport.update({
    id: '/campaigns/$id_/character',
    path: '/campaigns/$id/character',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/create': typeof AuthenticatedCampaignsCreateRoute
  '/campaigns/join': typeof AuthenticatedCampaignsJoinRoute
  '/campaigns/$id/character': typeof AuthenticatedCampaignsIdCharacterRoute
  '/campaigns/$id/play': typeof AuthenticatedCampaignsIdPlayRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/create': typeof AuthenticatedCampaignsCreateRoute
  '/campaigns/join': typeof AuthenticatedCampaignsJoinRoute
  '/campaigns/$id/character': typeof AuthenticatedCampaignsIdCharacterRoute
  '/campaigns/$id/play': typeof AuthenticatedCampaignsIdPlayRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/create': typeof AuthenticatedCampaignsCreateRoute
  '/_authenticated/campaigns/join': typeof AuthenticatedCampaignsJoinRoute
  '/_authenticated/campaigns/$id_/character': typeof AuthenticatedCampaignsIdCharacterRoute
  '/_authenticated/campaigns/$id_/play': typeof AuthenticatedCampaignsIdPlayRoute
  '/api/public/spotify/callback': typeof ApiPublicSpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/campaigns/$id'
    | '/campaigns/create'
    | '/campaigns/join'
    | '/campaigns/$id/character'
    | '/campaigns/$id/play'
    | '/api/public/spotify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/campaigns/$id'
    | '/campaigns/create'
    | '/campaigns/join'
    | '/campaigns/$id/character'
    | '/campaigns/$id/play'
    | '/api/public/spotify/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/create'
    | '/_authenticated/campaigns/join'
    | '/_authenticated/campaigns/$id_/character'
    | '/_authenticated/campaigns/$id_/play'
    | '/api/public/spotify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPublicSpotifyCallbackRoute: typeof ApiPublicSpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/join': {
      id: '/_authenticated/campaigns/join'
      path: '/campaigns/join'
      fullPath: '/campaigns/join'
      preLoaderRoute: typeof AuthenticatedCampaignsJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/create': {
      id: '/_authenticated/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/campaigns/create'
      preLoaderRoute: typeof AuthenticatedCampaignsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/spotify/callback': {
      id: '/api/public/spotify/callback'
      path: '/api/public/spotify/callback'
      fullPath: '/api/public/spotify/callback'
      preLoaderRoute: typeof ApiPublicSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$id_/play': {
      id: '/_authenticated/campaigns/$id_/play'
      path: '/campaigns/$id/play'
      fullPath: '/campaigns/$id/play'
      preLoaderRoute: typeof AuthenticatedCampaignsIdPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id_/character': {
      id: '/_authenticated/campaigns/$id_/character'
      path: '/campaigns/$id/character'
      fullPath: '/campaigns/$id/character'
      preLoaderRoute: typeof AuthenticatedCampaignsIdCharacterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsCreateRoute: typeof AuthenticatedCampaignsCreateRoute
  AuthenticatedCampaignsJoinRoute: typeof AuthenticatedCampaignsJoinRoute
  AuthenticatedCampaignsIdCharacterRoute: typeof AuthenticatedCampaignsIdCharacterRoute
  AuthenticatedCampaignsIdPlayRoute: typeof AuthenticatedCampaignsIdPlayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCampaignsCreateRoute: AuthenticatedCampaignsCreateRoute,
  AuthenticatedCampaignsJoinRoute: AuthenticatedCampaignsJoinRoute,
  AuthenticatedCampaignsIdCharacterRoute:
    AuthenticatedCampaignsIdCharacterRoute,
  AuthenticatedCampaignsIdPlayRoute: AuthenticatedCampaignsIdPlayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPublicSpotifyCallbackRoute: ApiPublicSpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
